# Write your MySQL query statement below
SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY AS SALARY
FROM DEPARTMENT AS D
JOIN EMPLOYEE AS E
ON D.ID = E.DEPARTMENTID
WHERE E.SALARY = (
    SELECT MAX(E2.SALARY)
    FROM EMPLOYEE AS E2
    WHERE E2.DEPARTMENTID = E.DEPARTMENTID
);